"""phase 3 encounters red flags

Revision ID: 07d5b9200705
Revises: 1e59f09f9a51
Create Date: 2026-09-07 23:17:59.244107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '07d5b9200705'
down_revision: Union[str, None] = '1e59f09f9a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Alembic does not drop native ENUM types on downgrade.
PHASE_3_ENUM_TYPES = ("red_flag_status", "red_flag_category", "red_flag_source")


def upgrade() -> None:
    # `op.add_column` does NOT create a native ENUM type — only `create_table`
    # does. The status column below is added by ALTER, so its type has to be
    # created explicitly first or the ALTER fails on an undefined type.
    bind = op.get_bind()
    for type_name, values in (
        ("red_flag_status", ("none", "active", "clinician_cleared")),
        ("red_flag_category", (
            "breathing", "chest", "bleeding", "consciousness",
            "neurological", "other",
        )),
        ("red_flag_source", ("rules", "ai_assist")),
    ):
        sa.Enum(*values, name=type_name).create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('red_flags',
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('category', postgresql.ENUM(name='red_flag_category', create_type=False), nullable=False),
    sa.Column('source', postgresql.ENUM(name='red_flag_source', create_type=False), server_default='rules', nullable=False),
    sa.Column('evidence', sa.String(length=300), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_by', sa.String(length=120), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_red_flags_encounter_id_encounters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_red_flags'))
    )
    op.create_index(op.f('ix_red_flags_category'), 'red_flags', ['category'], unique=False)
    op.create_index(op.f('ix_red_flags_encounter_id'), 'red_flags', ['encounter_id'], unique=False)
    op.add_column('encounters', sa.Column('red_flag_status', postgresql.ENUM(name='red_flag_status', create_type=False), server_default='none', nullable=False))
    op.add_column('encounters', sa.Column('red_flag_acknowledged_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('assistance_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('encounters', sa.Column('patient_confirmed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_encounters_red_flag_status'), 'encounters', ['red_flag_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encounters_red_flag_status'), table_name='encounters')
    op.drop_column('encounters', 'patient_confirmed')
    op.drop_column('encounters', 'submitted_at')
    op.drop_column('encounters', 'assistance_requested_at')
    op.drop_column('encounters', 'red_flag_acknowledged_at')
    op.drop_column('encounters', 'red_flag_status')
    op.drop_index(op.f('ix_red_flags_encounter_id'), table_name='red_flags')
    op.drop_index(op.f('ix_red_flags_category'), table_name='red_flags')
    op.drop_table('red_flags')
    # ### end Alembic commands ###
    for type_name in PHASE_3_ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
