"""phase 2 interview documents ayush

Revision ID: 1e59f09f9a51
Revises: 98bcd378da12
Create Date: 2026-09-07 22:49:28.449102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e59f09f9a51'
down_revision: Union[str, None] = '98bcd378da12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native ENUM types created implicitly by the CREATE TABLEs below. Alembic
# never drops them, which would break downgrade -> upgrade.
PHASE_2_ENUM_TYPES = (
    "conversation_status",
    "input_method",
    "extracted_entity_type",
    "lab_flag",
    "review_state",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ayush_assessments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('dashavidha', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ahara', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('vihara', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_ayush_assessments_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ayush_assessments'))
    )
    op.create_index(op.f('ix_ayush_assessments_patient_id'), 'ayush_assessments', ['patient_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'awaiting_review', 'confirmed', 'abandoned', name='conversation_status'), server_default='in_progress', nullable=False),
    sa.Column('current_section', sa.String(length=40), nullable=False),
    sa.Column('current_question_id', sa.String(length=80), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ai_fallback_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_conversation_sessions_encounter_id_encounters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_conversation_sessions_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_sessions'))
    )
    op.create_index(op.f('ix_conversation_sessions_encounter_id'), 'conversation_sessions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_patient_id'), 'conversation_sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_status'), 'conversation_sessions', ['status'], unique=False)
    op.create_table('conversation_answers',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=120), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('raw_answer', sa.Text(), nullable=False),
    sa.Column('normalized_answer', sa.Text(), nullable=False),
    sa.Column('input_method', sa.Enum('voice', 'text', 'touch', name='input_method'), server_default='text', nullable=False),
    sa.Column('extracted_items', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('ai_assisted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], name=op.f('fk_conversation_answers_session_id_conversation_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_answers'))
    )
    op.create_index(op.f('ix_conversation_answers_session_id'), 'conversation_answers', ['session_id'], unique=False)
    op.create_table('extracted_medical_data',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('diagnosis', 'medication', 'investigation', 'procedure', 'surgery', 'allergy', 'vital', 'note', name='extracted_entity_type'), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('numeric_value', sa.String(length=40), nullable=True),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('reference_range', sa.String(length=80), nullable=True),
    sa.Column('flag', sa.Enum('normal', 'low', 'high', 'unclear', name='lab_flag'), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), server_default='0.5', nullable=False),
    sa.Column('review_state', sa.Enum('unreviewed', 'accepted', 'rejected', name='review_state'), server_default='unreviewed', nullable=False),
    sa.Column('extractor', sa.String(length=40), server_default='rules', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_extracted_medical_data_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_medical_data'))
    )
    op.create_index(op.f('ix_extracted_medical_data_document_id'), 'extracted_medical_data', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_medical_data_entity_type'), 'extracted_medical_data', ['entity_type'], unique=False)
    op.add_column('documents', sa.Column('ocr_engine', sa.String(length=40), nullable=True))
    op.add_column('documents', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('documents', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('medical_profiles', sa.Column('chief_complaint', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('medical_profiles', sa.Column('history_of_present_illness', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('medical_profiles', sa.Column('drug_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('medical_profiles', sa.Column('review_of_systems', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medical_profiles', 'review_of_systems')
    op.drop_column('medical_profiles', 'drug_history')
    op.drop_column('medical_profiles', 'history_of_present_illness')
    op.drop_column('medical_profiles', 'chief_complaint')
    op.drop_column('documents', 'document_date')
    op.drop_column('documents', 'ocr_confidence')
    op.drop_column('documents', 'ocr_engine')
    op.drop_index(op.f('ix_extracted_medical_data_entity_type'), table_name='extracted_medical_data')
    op.drop_index(op.f('ix_extracted_medical_data_document_id'), table_name='extracted_medical_data')
    op.drop_table('extracted_medical_data')
    op.drop_index(op.f('ix_conversation_answers_session_id'), table_name='conversation_answers')
    op.drop_table('conversation_answers')
    op.drop_index(op.f('ix_conversation_sessions_status'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_patient_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_encounter_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_ayush_assessments_patient_id'), table_name='ayush_assessments')
    op.drop_table('ayush_assessments')
    # ### end Alembic commands ###
    for type_name in PHASE_2_ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
