"""phase 1 foundation

Revision ID: 98bcd378da12
Revises: 
Create Date: 2026-09-07 21:51:45.767049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98bcd378da12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Native ENUM types are created implicitly by the CREATE TABLE statements
# above, but Alembic never drops them. Listing them here keeps
# `downgrade base` -> `upgrade head` repeatable.
ENUM_TYPES = (
    "abha_verification_status",
    "consent_purpose",
    "consent_status",
    "contrast_mode",
    "difficulty_level",
    "digital_comfort",
    "document_type",
    "encounter_priority",
    "encounter_status",
    "font_size",
    "gender",
    "interaction_preference",
    "interface_mode",
    "language",
    "onboarding_status",
    "preference_source",
    "preferred_interaction",
    "processing_status",
    "visit_type",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_challenges',
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_challenges'))
    )
    op.create_index(op.f('ix_otp_challenges_mobile_number'), 'otp_challenges', ['mobile_number'], unique=False)
    op.create_table('patients',
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', 'undisclosed', name='gender'), nullable=True),
    sa.Column('preferred_language', sa.Enum('en', 'hi', name='language'), server_default='en', nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=160), nullable=True),
    sa.Column('emergency_contact_number', sa.String(length=20), nullable=True),
    sa.Column('emergency_contact_relation', sa.String(length=60), nullable=True),
    sa.Column('onboarding_status', sa.Enum('abha_pending', 'personal_info_pending', 'assessment_pending', 'preferences_pending', 'consent_pending', 'medical_profile_pending', 'completed', name='onboarding_status'), server_default='abha_pending', nullable=False),
    sa.Column('is_demo', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients'))
    )
    op.create_index(op.f('ix_patients_mobile_number'), 'patients', ['mobile_number'], unique=True)
    op.create_index(op.f('ix_patients_onboarding_status'), 'patients', ['onboarding_status'], unique=False)
    op.create_table('abha_profiles',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('abha_id', sa.String(length=64), nullable=True),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'failed', 'skipped', name='abha_verification_status'), server_default='unverified', nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('is_mock', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_abha_profiles_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abha_profiles'))
    )
    op.create_index(op.f('ix_abha_profiles_abha_id'), 'abha_profiles', ['abha_id'], unique=False)
    op.create_index(op.f('ix_abha_profiles_patient_id'), 'abha_profiles', ['patient_id'], unique=True)
    op.create_table('accessibility_assessments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('digital_comfort', sa.Enum('very_comfortable', 'somewhat_comfortable', 'need_help', 'prefer_simple', name='digital_comfort'), nullable=False),
    sa.Column('preferred_interaction', sa.Enum('speaking', 'touching', 'both', name='preferred_interaction'), nullable=False),
    sa.Column('reading_difficulty', sa.Enum('none', 'sometimes', 'yes', name='difficulty_level'), nullable=False),
    sa.Column('hearing_difficulty', sa.Enum('none', 'sometimes', 'yes', name='difficulty_level'), nullable=False),
    sa.Column('vision_difficulty', sa.Enum('none', 'sometimes', 'yes', name='difficulty_level'), nullable=False),
    sa.Column('additional_needs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('additional_notes', sa.Text(), nullable=True),
    sa.Column('recommendation', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('age_at_assessment', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_accessibility_assessments_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accessibility_assessments'))
    )
    op.create_index(op.f('ix_accessibility_assessments_patient_id'), 'accessibility_assessments', ['patient_id'], unique=False)
    op.create_table('consents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.Enum('health_data_collection', 'share_with_treating_doctor', 'abha_linkage', name='consent_purpose'), nullable=False),
    sa.Column('status', sa.Enum('granted', 'declined', 'revoked', name='consent_status'), nullable=False),
    sa.Column('text_version', sa.String(length=32), server_default='2026-01', nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_consents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consents_purpose'), 'consents', ['purpose'], unique=False)
    op.create_table('encounters',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'awaiting_review', 'completed', 'cancelled', name='encounter_status'), server_default='draft', nullable=False),
    sa.Column('priority', sa.Enum('routine', 'priority', 'urgent', name='encounter_priority'), server_default='routine', nullable=False),
    sa.Column('visit_type', sa.Enum('first_visit', 'follow_up', name='visit_type'), server_default='first_visit', nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('structured_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_encounters_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_encounters'))
    )
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.create_table('medical_profiles',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('past_medical_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('surgical_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('current_medications', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('family_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('personal_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('previous_investigations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('additional_information', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_medical_profiles_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_profiles'))
    )
    op.create_index(op.f('ix_medical_profiles_patient_id'), 'medical_profiles', ['patient_id'], unique=True)
    op.create_table('patient_preferences',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('interface_mode', sa.Enum('standard', 'easy', name='interface_mode'), server_default='standard', nullable=False),
    sa.Column('font_size', sa.Enum('normal', 'large', 'extra_large', name='font_size'), server_default='normal', nullable=False),
    sa.Column('contrast_mode', sa.Enum('normal', 'high', name='contrast_mode'), server_default='normal', nullable=False),
    sa.Column('audio_guidance', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('interaction_preference', sa.Enum('voice', 'touch', 'hybrid', name='interaction_preference'), server_default='touch', nullable=False),
    sa.Column('language', sa.Enum('en', 'hi', name='language'), server_default='en', nullable=False),
    sa.Column('source', sa.Enum('recommended', 'customized', name='preference_source'), server_default='recommended', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_patient_preferences_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_preferences'))
    )
    op.create_index(op.f('ix_patient_preferences_patient_id'), 'patient_preferences', ['patient_id'], unique=True)
    op.create_table('documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('prescription', 'lab_report', 'discharge_summary', 'other', name='document_type'), server_default='other', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'needs_review', name='processing_status'), server_default='pending', nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_error', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], name=op.f('fk_documents_encounter_id_encounters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name=op.f('fk_documents_patient_id_patients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_encounter_id'), 'documents', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_encounter_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_patient_preferences_patient_id'), table_name='patient_preferences')
    op.drop_table('patient_preferences')
    op.drop_index(op.f('ix_medical_profiles_patient_id'), table_name='medical_profiles')
    op.drop_table('medical_profiles')
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_consents_purpose'), table_name='consents')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_accessibility_assessments_patient_id'), table_name='accessibility_assessments')
    op.drop_table('accessibility_assessments')
    op.drop_index(op.f('ix_abha_profiles_patient_id'), table_name='abha_profiles')
    op.drop_index(op.f('ix_abha_profiles_abha_id'), table_name='abha_profiles')
    op.drop_table('abha_profiles')
    op.drop_index(op.f('ix_patients_onboarding_status'), table_name='patients')
    op.drop_index(op.f('ix_patients_mobile_number'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_otp_challenges_mobile_number'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    # ### end Alembic commands ###
    for type_name in ENUM_TYPES:
        op.execute(sa.text(f"DROP TYPE IF EXISTS {type_name}"))
