"""phase 4 care system ayush depth

Revision ID: c32f70b87536
Revises: 07d5b9200705
Create Date: 2026-09-08 00:46:26.808011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c32f70b87536'
down_revision: Union[str, None] = '07d5b9200705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `op.add_column` does not create a native ENUM type — only `create_table`
    # does — so the type has to exist before the ALTERs below.
    sa.Enum(
        "allopathy", "ayurveda", "homoeopathy", "unani", "siddha",
        "yoga_naturopathy", "unsure",
        name="care_system",
    ).create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ayush_assessments', sa.Column('ashtasthana', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('ayush_assessments', sa.Column('lifestyle', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('encounters', sa.Column('care_system', postgresql.ENUM(name='care_system', create_type=False), nullable=True))
    op.create_index(op.f('ix_encounters_care_system'), 'encounters', ['care_system'], unique=False)
    op.add_column('patients', sa.Column('preferred_care_system', postgresql.ENUM(name='care_system', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'preferred_care_system')
    op.drop_index(op.f('ix_encounters_care_system'), table_name='encounters')
    op.drop_column('encounters', 'care_system')
    op.drop_column('ayush_assessments', 'lifestyle')
    op.drop_column('ayush_assessments', 'ashtasthana')
    # ### end Alembic commands ###
    op.execute(sa.text("DROP TYPE IF EXISTS care_system"))
